import google.generativeai as genai

def interview_with_gemini(job_profile, resume_text, api_key):
  """
  This function uses the Gemini API to generate interview questions based on a job profile and resume.

  Args:
      job_profile: The job title or position the candidate is applying for (str).
      resume_text: The extracted text content of the candidate's resume (str).
      api_key: Your Google Cloud Project API key for accessing Gemini (str).

  Returns:
      A list of interview questions generated by Gemini (list[str]).
  """

  # Configure Gemini with your API key
  genai.configure(api_key=api_key)

  # Model selection - Choose a model suitable for text generation (replace if needed)
  model = genai.GenerativeModel('gemini-1.5-flash')

  # Construct the prompt for Gemini
  prompt = f"""
  **Job Profile:** {job_profile}

  **Resume:**
  {resume_text}

  **Task:** Generate a list of interview questions for this candidate based on the provided job profile and resume.
  """

  # Generate interview questions using Gemini
  response = model.generate_content(prompt)
  questions = response.text.strip().split('\n')  # Split response into individual questions

  return questions

# Example usage (replace with your API key)
if __name__ == "__main__":
  your_api_key = "AIzaSyBKAMX4Lr7A74R2Cw56ZpW6-iEDCB1OeRM"
  job_profile = "Software Engineer"
  resume_text = "Jai Verma     +91 7011345425                                                                                                                                textjaiverma@gmail.com 2K21/CO/210      EDUCATION            B.TECH(Computer Engineering)     2021-2025      Delhi Technological University, New Delhi     76.26 %       CBSE (Class XII)      2021     Manava Bharati India International School     95.8 %       CBSE (Class X)      2019     Manava Bharati India International School       90.4 %        ● Awarded the Medal of Honor for scoring the maximum in Mathematics in class X and XII.         INTERNSHIPS    Software Intern at Defence Research and Development Organization (DRDO), New Delhi    June 2023 – August 2023    ● Led a project for improving Hand-Eye Coordination   ● Worked on Natural Language Processing and LLM Integration     ACADEMIC PROJECT     LocalGPT     ● Running Large Language Models on local machine with inbuilt Chatbot for your documents.            Tech Stack:Natural Language Processing and LLM Integration     ACADEMIC PROJECT     LocalGPT     ● Running Large Language Models on local machine with inbuilt Chatbot for your documents.            Tech Stack: python, torch, huggingface, langchain, transformers  Real Estate Price Predictions     ● Utilizing Machine Learning to predict prices in real estate.            Tech Stack: tensorﬂow, GridSearchCV  SynthAI — Web App       ●  Using Large Language Models to conduct Mock Interviews for Software Developers                    Tech Stack: ﬂask, html, css, bootstrap, OpenAI, langchain, transformers              TECHNICAL SKILLS          C/C++, python, Arduino,  MySQL, HTML, CSS Git, Unity, VSCode, Google Colab, AI Studio AI, ML, DL, NLP , LLM IntegraLon  POSITIONS OF RESPONSIBILITY     ● As Member and Coordinator in Indian Game Theory Society     ○ This position demanded me to increase my knowledge of Game Theory and Strategy development and spread it to my fellow peers.     ○ Coordinating theand Coordinator in Indian Game Theory Society     ○ This position demanded me to increase my knowledge of Game Theory and Strategy development and spread it to my fellow peers.     ○ Coordinating the said Games in various fests.      OTHER INFORMATION     ● LinkedIn Profile: https://www.linkedin.com/in/jai-verma-399692223     ● GitHub Profile: https://github.com/textjai-16"  # Replace with actual resume text

  questions = interview_with_gemini(job_profile, resume_text, your_api_key)

  print("Generated Interview Questions:")
  for question in questions:
    print(question)


#candidate: i want you to act as an interviewer and conduct an interview for the job position of a software engineer, your response should be to begin the interview; interviewer: Welcome to our company. I'm pleased to meet you today as we consider your application for the Software Engineer position. The role requires strong technical skills, creativity, and problem-solving abilities. Let's begin with some introductions. Could you please tell me a bit about yourself? What programming languages are you most proficient in, and what projects have you worked on that demonstrate your skills as a software engineer? I'm looking forward to learning more about your background, experiences, and how they align with our team's needs. Let's dive into the details of your application and discuss your potential contributions to our company. Thank you!; Candidate: I am fluent in python and c++ and i have experience developing web applications, i also sahre a keen intereest in large language models and artificical intelligence; now ask teh next question of the interview